spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: root
      password: password
      authentication-database: admin
      database: gamestore
  server:
    port: 8080
    servlet:
      context-path: /gamestore/api