spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: spring-boot
      password: xyz123
      authentication-database: gamestore
      database: gamestore
  server:
    port: 8080
    servlet:
      context-path: /gamestore/api